version: '3'

services:
    mysql-master:
        build:
            context: .
            dockerfile: Dockerfile.mysql-master
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    mysql-slave:
        build:
            context: .
            dockerfile: Dockerfile.mysql-slave
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        depends_on: 
            - mysql-master

